version: "3.5"
services:
  charon-validator-1:
    build:
      context: charon-validator
      dockerfile: Dockerfile.teku
      args:
        UPSTREAM_VERSION: v0.17.2
        VALIDATOR_CLIENT_VERSION: 23.11.0
        CLUSTER_ID: 1
    restart: on-failure
    volumes:
      - "charon-1-data:/opt/charon/.charon"
      - "validator-1-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3911"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3931"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-1
      - ENABLE_MEV_BOOST=false
      - CHARON_EXTRA_OPTS
      - DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - VALIDATOR_EXTRA_OPTS
    ports:
      - "3911:3911/tcp"
      - "3931:3931/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-1.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-validator-2:
    build:
      context: charon-validator
      dockerfile: Dockerfile.teku
      args:
        UPSTREAM_VERSION: v0.17.2
        VALIDATOR_CLIENT_VERSION: 23.11.0
        CLUSTER_ID: 2
    restart: on-failure
    volumes:
      - "charon-2-data:/opt/charon/.charon"
      - "validator-2-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3912"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3932"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-2
      - ENABLE_MEV_BOOST=false
      - CHARON_EXTRA_OPTS
      - DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - VALIDATOR_EXTRA_OPTS
    ports:
      - "3912:3912/tcp"
      - "3932:3932/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-2.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-validator-3:
    build:
      context: charon-validator
      dockerfile: Dockerfile.teku
      args:
        UPSTREAM_VERSION: v0.17.2
        VALIDATOR_CLIENT_VERSION: 23.11.0
        CLUSTER_ID: 3
    restart: on-failure
    volumes:
      - "charon-3-data:/opt/charon/.charon"
      - "validator-3-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3913"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3933"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-3
      - ENABLE_MEV_BOOST=false
      - CHARON_EXTRA_OPTS
      - DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - VALIDATOR_EXTRA_OPTS
    ports:
      - "3913:3913/tcp"
      - "3933:3933/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-3.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-validator-4:
    build:
      context: charon-validator
      dockerfile: Dockerfile.teku
      args:
        UPSTREAM_VERSION: v0.17.2
        VALIDATOR_CLIENT_VERSION: 23.11.0
        CLUSTER_ID: 4
    restart: on-failure
    volumes:
      - "charon-4-data:/opt/charon/.charon"
      - "validator-4-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3914"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3934"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-4
      - ENABLE_MEV_BOOST=false
      - CHARON_EXTRA_OPTS
      - DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - VALIDATOR_EXTRA_OPTS
    ports:
      - "3914:3914/tcp"
      - "3934:3934/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-4.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-validator-5:
    build:
      context: charon-validator
      dockerfile: Dockerfile.teku
      args:
        UPSTREAM_VERSION: v0.17.2
        VALIDATOR_CLIENT_VERSION: 23.11.0
        CLUSTER_ID: 5
    restart: on-failure
    volumes:
      - "charon-5-data:/opt/charon/.charon"
      - "validator-5-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3915"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3935"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-5
      - ENABLE_MEV_BOOST=false
      - CHARON_EXTRA_OPTS
      - DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - VALIDATOR_EXTRA_OPTS
    ports:
      - "3915:3915/tcp"
      - "3935:3935/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-5.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
volumes:
  charon-1-data: {}
  charon-2-data: {}
  charon-3-data: {}
  charon-4-data: {}
  charon-5-data: {}
  validator-1-data: {}
  validator-2-data: {}
  validator-3-data: {}
  validator-4-data: {}
  validator-5-data: {}
