version: "3.5"
services:
  charon-teku-1:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.0
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 1
    restart: on-failure
    volumes:
      - "charon-1-data:/opt/charon/.charon"
      - "teku-1-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3911"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3931"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-1
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - TEKU_EXTRA_OPTS
    ports:
      - "3911:3911/tcp"
      - "3931:3931/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-1.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
volumes:
  charon-1-data: {}
  teku-1-data: {}
