version: "3.5"
services:
  charon-1:
    build:
      context: ./charon
      args:
        UPSTREAM_VERSION: v0.17.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
      - CLUSTER_ID=1
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku-1:
    build:
      context: ./teku
      args:
        TEKU_VERSION: 23.10.0
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      - TEKU_NETWORK=prater
      - LOG_TYPE=INFO
      - TEKU_BEACON_NODE_API_ENDPOINT="http://charon:3600"
      - TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - VALIDATORS_GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - CLUSTER_ID=1
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    security_opt:
      - "seccomp:unconfined"
  charon-2:
    build:
      context: ./charon
      args:
        UPSTREAM_VERSION: v0.17.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
      - CLUSTER_ID=2
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku-2:
    build:
      context: ./teku
      args:
        TEKU_VERSION: 23.10.0
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      - TEKU_NETWORK=prater
      - LOG_TYPE=INFO
      - TEKU_BEACON_NODE_API_ENDPOINT="http://charon:3600"
      - TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - VALIDATORS_GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - CLUSTER_ID=2
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    security_opt:
      - "seccomp:unconfined"
  charon-3:
    build:
      context: ./charon
      args:
        UPSTREAM_VERSION: v0.17.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
      - CLUSTER_ID=3
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku-3:
    build:
      context: ./teku
      args:
        TEKU_VERSION: 23.10.0
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      - TEKU_NETWORK=prater
      - LOG_TYPE=INFO
      - TEKU_BEACON_NODE_API_ENDPOINT="http://charon:3600"
      - TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - VALIDATORS_GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - CLUSTER_ID=3
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    security_opt:
      - "seccomp:unconfined"
  charon-4:
    build:
      context: ./charon
      args:
        UPSTREAM_VERSION: v0.17.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
      - CLUSTER_ID=1
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku-4:
    build:
      context: ./teku
      args:
        TEKU_VERSION: 23.10.0
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      - TEKU_NETWORK=prater
      - LOG_TYPE=INFO
      - TEKU_BEACON_NODE_API_ENDPOINT="http://charon:3600"
      - TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - VALIDATORS_GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - CLUSTER_ID=4
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    security_opt:
      - "seccomp:unconfined"
  charon-5:
    build:
      context: ./charon
      args:
        UPSTREAM_VERSION: v0.17.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
      - CLUSTER_ID=5
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku-5:
    build:
      context: ./teku
      args:
        TEKU_VERSION: 23.10.0
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      - TEKU_NETWORK=prater
      - LOG_TYPE=INFO
      - TEKU_BEACON_NODE_API_ENDPOINT="http://charon:3600"
      - TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT="0x0000000000000000000000000000000000000000"
      - VALIDATORS_GRAFFITI=validating_from_DAppNode
      - EXTRA_OPTS
      - CLUSTER_ID=5
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
    security_opt:
      - "seccomp:unconfined"
volumes:
  charon-data: {}
  teku-prater-data: {}
