version: "3.5"
services:
  charon-teku-1:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.2
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 1
    restart: on-failure
    volumes:
      - "charon-1-data:/opt/charon/.charon"
      - "teku-1-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3911"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3931"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-teku-1
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - TEKU_EXTRA_OPTS
    ports:
      - "3911:3911/tcp"
      - "3931:3931/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-1.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-teku-2:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.2
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 2
    restart: on-failure
    volumes:
      - "charon-2-data:/opt/charon/.charon"
      - "teku-2-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3912"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3932"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-teku-2
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - TEKU_EXTRA_OPTS
    ports:
      - "3912:3912/tcp"
      - "3932:3932/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-2.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-teku-3:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.2
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 3
    restart: on-failure
    volumes:
      - "charon-3-data:/opt/charon/.charon"
      - "teku-3-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3913"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3933"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-teku-3
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - TEKU_EXTRA_OPTS
    ports:
      - "3913:3913/tcp"
      - "3933:3933/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-3.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-teku-4:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.2
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 4
    restart: on-failure
    volumes:
      - "charon-4-data:/opt/charon/.charon"
      - "teku-4-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3914"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3934"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-teku-4
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - TEKU_EXTRA_OPTS
    ports:
      - "3914:3914/tcp"
      - "3934:3934/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-4.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
  charon-teku-5:
    build:
      context: charon-teku
      args:
        UPSTREAM_VERSION: v0.17.2
        TEKU_VERSION: 23.11.0
        CLUSTER_ID: 5
    restart: on-failure
    volumes:
      - "charon-5-data:/opt/charon/.charon"
      - "teku-5-data:/opt/teku/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3915"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3935"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-teku-5
      - TEKU_LOGGING=INFO
      - >-
        TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT=0x0000000000000000000000000000000000000000
      - TEKU_VALIDATORS_GRAFFITI=validating_from_DAppNode
      - JAVA_OPTS=-Xmx5g
      - TEKU_EXTRA_OPTS
    ports:
      - "3915:3915/tcp"
      - "3935:3935/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-teku-5.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.1"
volumes:
  charon-1-data: {}
  charon-2-data: {}
  charon-3-data: {}
  charon-4-data: {}
  charon-5-data: {}
  teku-1-data: {}
  teku-2-data: {}
  teku-3-data: {}
  teku-4-data: {}
  teku-5-data: {}
