version: "3.5"
services:
  charon:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v0.13.0
    image: "charon.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
    volumes:
      - "charon-data:/opt/charon/.charon"
    environment:
      - DEFINITION_FILE
      - CHARON_LOG_LEVEL=info
      - CHARON_LOG_FORMAT=console
      - >-
        CHARON_P2P_RELAYS=https://0.relay.obol.tech/enr,http://bootnode.lb.gcp.obol.tech:3640/enr
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3611"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3631"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon
    ports:
      - "3611:3611/tcp"
      - "3631:3631/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
  teku:
    build:
      context: ./teku
      args:
        UPSTREAM_VERSION: 23.1.1
    restart: unless-stopped
    volumes:
      - "teku-prater-data:/opt/teku/data"
    environment:
      TEKU_NETWORK: prater
      LOG_TYPE: INFO
      TEKU_BEACON_NODE_API_ENDPOINT: "http://charon:3600"
      TEKU_VALIDATORS_PROPOSER_DEFAULT_FEE_RECIPIENT: "0x0000000000000000000000000000000000000000"
      VALIDATORS_GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
    image: "teku.obol-distributed-validator-goerli.dnp.dappnode.eth:0.1.0"
volumes:
  charon-data: {}
  teku-prater-data: {}
